version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 8000:9000
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_api_db
    ports:
      - 3306:3306
